"""route group names unique per user

Revision ID: 34756a4a8d9b
Revises: f2a3b4c5d6e7
Create Date: 2026-04-25 10:02:23.869742

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34756a4a8d9b'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_daily_cheapest_per_group'), 'daily_cheapest_prices', type_='unique')
    op.create_unique_constraint(None, 'daily_cheapest_prices', ['origin', 'destination', 'depart_date'])
    op.create_unique_constraint('uq_routegroups_user_name', 'route_groups', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_routegroups_user_name', 'route_groups', type_='unique')
    op.drop_constraint(None, 'daily_cheapest_prices', type_='unique')
    op.create_unique_constraint(op.f('uq_daily_cheapest_per_group'), 'daily_cheapest_prices', ['route_group_id', 'origin', 'destination', 'depart_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
